### ISSUE TITLE
Declarator list in structures/unions can be empty

### ISSUE THREAD

**Issue by Kerilk** [oggy/cast#21]
Apparently the C99 grammar allows empty declarator list in structures.
The following snippet:
```c
int main() {
  int;
  struct {
    int;
    union {
      int a;
      float b;
    };
  } c;
  return 0;
}
```
when compiled with `gcc test.c -std=c99 -pedantic` yields:
```
test.c: In function ‘main’:
test.c:2:3: warning: useless type name in empty declaration
    2 |   int;
      |   ^~~
test.c:4:8: warning: declaration does not declare anything
    4 |     int;
      |        ^
test.c:8:6: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
    8 |     };
      |      ^
test.c:3:3: warning: struct has no named members [-Wpedantic]
    3 |   struct {
      |   ^~~~~~
```
cast chokes on the first declaration without declarator inside the structure:
```
C::ParseError (4:0: parse error on SEMICOLON (SEMICOLON))
```
I have a patch for this:
```diffdiff --git a/lib/cast/c.y b/lib/cast/c.y
index 189d585..c145147 100644
--- a/lib/cast/c.y
+++ b/lib/cast/c.y
@@ -173,6 +173,7 @@ struct_declaration_list
 # Returns Declaration
 struct_declaration
   : specifier_qualifier_list struct_declarator_list SEMICOLON {result = make_declaration(val[0][0], val[0][1], val[1])}
+  | specifier_qualifier_list                        SEMICOLON {result = make_declaration(val[0][0], val[0][1], NodeArray[])}
 
 # Returns {Pos, [Symbol]}
 specifier_qualifier_list
```
This does not break any test. This also allows to parse anonymous structs and unions that are frequently used nowadays (which are not supported in C99, but apparently not at the parser level).
So this brings up a number of question:
 - Is this something you would be willing to add to cast?
 - Would you prefer it as an optional feature?

**Comment by oggy** [comment]
Sure, want to submit a PR? I think just allowing it by default is fine since it's backwards-compatible.

FWIW I think GCC is not technically correct on this one though.

![image](https://user-images.githubusercontent.com/11112/87483265-5285f880-c601-11ea-9569-a0a973c395c6.png)

**Comment by Kerilk** [comment]
I will submit a pull request indeed. Thanks for the quick answer.
